config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/thank'
  post 'dashboard/donate'
  get 'dashboard/give'

  root :to => "dashboard#home"

  resources :donations do
    collection do
      post 'create'
    end
  end

  devise_for :user
end

app/models/donation.rb
class Donation < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
  end

  def thank
  end

  def donate
    if params[:email] == params[:email_confirm]
      @user = User.create({:email=>params[:email], :password=>"password", :password_confirmation=>"password"})
    end
    @donation_amount = params[:donation_amounts][:predefined] || params[:donation_amounts][:custom_amount]
    @recurring_frequency = params[:recurring_frequency]
    redirect_to dashboard_give_path(   :amount => @donation_amount, :recurring_frequency => @recurring_frequency)
    # binding.pry

  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

    def create
      # binding.pry
      @productFamily = Chargify::ProductFamily.find_by_handle('donationtest')
      if params[:email].nil?
         params[:email] = "asdf@asdf.com"
      end
      @customer = createCustomer(params)
      if @customer.id.present?
         params[:product_family_id] = @productFamily.id
         @product = createProduct(params)
      end

      if @product.id.present?
         @subscription = createSubscription(params)
        # binding.pry
      end
      redirect_to dashboard_thank_path(   :amount => @donation_amount, :recurring_frequency => @recurring_frequency)
    end

    def createCustomer(params)
      @customer = Chargify::Customer.create(:first_name=> params[:first_name], :last_name=>params[:last_name], :email=>params[:email])
    end

    def createProduct(params)
      @params = params

      params[:name] ||= "Donation by " + @customer.first_name
      params[:handle] ||= @customer.first_name.downcase()+ @customer.last_name.downcase()
      params[:price_in_cents] =  params[:donation_amount].to_f * 100 || "100"
      params[:interval] ||= "1"
      Chargify::Product.create( { "name" => params[:name], "handle" => params[:handle], "description" => params[:description], "accounting_code" => params[:accounting_code], "request_credit_card":true, "price_in_cents" => params[:price_in_cents], "interval" => params[:interval], "interval_unit":"month", "auto_create_signup_page": false ,"product_family_id" => params[:product_family_id]})
    end

    def createSubscription(params)
      # //for testing
      params[:expiration] = DateTime.now + 1.year
      params[:card_number] = 1

      Chargify::Subscription.create(
        :customer_id => @customer.id,
        :product_handle => @product.handle,
        :credit_card_attributes => {
          :first_name => params[:first_name],
          :last_name => params[:first_name],
          :expiration_month => params[:expiration].month,
          :expiration_year => params[:expiration].year,
          :full_number => params[:card_number]
        }
      )
    end



  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/dashboard/home.html.slim
/ h1 Welcome to the Donation Page

form#donation_form.clearfix accept-charset="UTF-8" action="/dashboard/donate" method="post" 
  h3.step-title style="color:#005983;background-color:#BDE724;" 
    .field.field-name-field-donation-title.field-type-text.field-label-hidden
      .field-items
        .field-item.even What can you give?


  #edit-donation-amounts.clearfix.form-wrapper
    #edit-donation-amounts-predefined.form-radios
      .form-item.form-type-radio
        input#donation_amount-0.form-radio name="donation_amounts[predefined]" type="radio" value="100" /
        label.option for="donation_amount-0"  $100
      .form-item.form-type-radio
        input#donation_amount-1.form-radio name="donation_amounts[predefined]" type="radio" value="250" /
        label.option for="donation_amount-1"  $250
      .form-item.form-type-radio
        input#donation_amount-2.form-radio name="donation_amounts[predefined]" type="radio" value="500" /
        label.option for="donation_amount-2"  $500
      .form-item.form-type-radio
        input#donation_amount-3.form-radio name="donation_amounts[predefined]" type="radio" value="1000" /
        label.option for="donation_amount-3"  $1,000
      .form-item.form-type-radio
        input#donation_amount-4.form-radio name="donation_amounts[predefined]" type="radio" value="2500" /
        label.option for="donation_amount-4"  $2,500
      .form-item.form-type-radio style=("display: none;") 
        label.option for="edit-donation-amounts-predefined-other"  Custom Amount
      .form-item.form-type-textfield.
        label.element-invisible for="donation_custom_amount " style=("display: none;")  Other amount
        span.field-prefix
          span.prefix $
        input#edit-donation-amounts-custom-amount.form-text.placeholder maxlength="128" name="donation_amounts[custom_amount]" placeholder=("Other  ")  type="number" value="" /
  .form-item.form-type-select.form-item-recurring-payment-options
    span.field-prefix Choose frequency of donation
    select#recurring_frequency.form-select name="recurring_frequency" 
      option value="1"  One time only
      option value="1"  Monthly
      option value="3"  Quarterly
      option value="12"  Yearly
  #edit-account.form-wrapper
    #edit-nologin.form-wrapper
      .form-item.form-type-textfield.form-item-email
        label.element-invisible for="edit-email"  E-mail
        input#edit-email.form-text maxlength="128" name="email" placeholder="E-mail" size="46" type="text" value="" /
      .form-item.form-type-textfield.form-item-email-confirm
        label.element-invisible for="edit-email-confirm"  E-mail (confirm)
        input#edit-email-confirm.form-text maxlength="128" name="email_confirm" placeholder=("Retype E-mail ") size="38" type="text" value="" /
      input#register.form-submit name="op" type="submit" value="Register" /

app/views/dashboard/thank.html.slim
h1 You just donated #{@amount}
p Thank you   

app/views/donations/_form.html.slim
= form_for @donation do |f|
  - if @donation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@donation.errors.count, "error")} prohibited this donation from being saved:"
      ul
        - @donation.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/donations/edit.html.slim
h1 Editing donation

== render 'form'

= link_to 'Show', @donation
'|
= link_to 'Back', donations_path

app/views/donations/index.html.slim
h1 Listing donations

table
  thead
    tr
      th
      th
      th

  tbody
    - @donations.each do |donation|
      tr
        td = link_to 'Show', donation
        td = link_to 'Edit', edit_donation_path(donation)
        td = link_to 'Destroy', donation, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Donation', new_donation_path

app/views/donations/new.html.slim
h1 New donation

== render 'form'

= link_to 'Back', donations_path

app/views/donations/show.html.slim
p#notice = notice


= link_to 'Edit', edit_donation_path(@donation)
'|
= link_to 'Back', donations_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChargifyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>